Repository zoobc/zoobc-sdk, pull requests merged in 2021-03, with the labels that each got.

#345 Fixing error semantic release
  .gitignore
  package.json
  yarn.lock
Labels: SDK, bug

#346 changes on liquid
  package.json
  src/LiquidTransaction.ts
  src/helper/transaction-builder/liquid-transaction.ts
Labels: bug, enhancement

#348 Fixing Bug Cannot find name EscrowTransactionInterface
  package.json
  src/LiquidTransaction.ts
  src/helper/transaction-builder/liquid-transaction.ts
Labels: SDK, bug

#349 fix some variable and export it
  package.json
  src/LiquidTransaction.ts
  src/helper/transaction-builder/liquid-transaction.ts
  src/index.ts
Labels: enhancement

#351 Fixing error cannot find namespace 'GetLiquidTransactionsResponse'.
  package.json
  src/LiquidTransaction.ts
Labels: SDK, bug

#352 fix bug on liquid timestamp
  package.json
  src/helper/transaction-builder/liquid-transaction.ts
  src/helper/wallet/Transaction.ts
Labels: bug

#353 Add Liquid Bytes on Send ZBC Builder
  examples/react/src/App.js
  examples/react/src/Liquid.js
  examples/react/src/SignSendZBC.js
  examples/react/src/SignSendZBCWithEid.js
  examples/react/src/SignSendZBCWithEthereum.js
  package.json
  src/LiquidTransaction.ts
  src/Transactions.ts
  src/helper/transaction-builder/liquid-transaction.ts
  src/helper/transaction-builder/send-money.ts
  src/helper/wallet/Liquid.ts
  src/helper/wallet/Transaction.ts
Labels: SDK, enhancement

#354 adding liquid example
  examples/react/src/Liquid.js
  package.json
  src/Transactions.ts
  src/helper/utils.ts
  src/helper/wallet/Transaction.ts
Labels: example

#356 Add Mempol Liquid Transaction
  examples/react/src/App.js
  examples/react/src/Mempol.js
  package.json
  src/helper/transaction-builder/liquid-transaction.ts
  src/helper/transaction-builder/post-transaction.ts
Labels: SDK, enhancement

#357 Add Transaction Type String in Mempol
  examples/react/src/Mempol.js
  package.json
  src/helper/wallet/Mempool.ts
Labels: SDK, enhancement

#358 Fixing Buffer Message in Builder
  package.json
  src/helper/transaction-builder/claim-node.ts
  src/helper/transaction-builder/escrow-transaction.ts
  src/helper/transaction-builder/fee-vote.ts
  src/helper/transaction-builder/liquid-transaction.ts
  src/helper/transaction-builder/multisignature.ts
  src/helper/transaction-builder/register-node.ts
  src/helper/transaction-builder/remove-account-dataset.ts
  src/helper/transaction-builder/remove-node.ts
  src/helper/transaction-builder/setup-account-dataset.ts
  src/helper/transaction-builder/update-node.ts
Labels: SDK, bug

#360 Update Example Stoped Liquid
  examples/react/src/Liquid.js
  grpc/model/batchReceipt_pb.d.ts
  grpc/model/batchReceipt_pb.js
  grpc/model/publishedReceipt_pb.d.ts
  grpc/model/publishedReceipt_pb.js
  grpc/model/receipt_pb.d.ts
  grpc/model/receipt_pb.js
  package.json
  src/LiquidTransaction.ts
  src/helper/transaction-builder/liquid-transaction.ts
Labels: SDK, example

#362 [ENHANCEMENT] Remove instruction validation on escrow tx
  package.json
  src/helper/transaction-builder/escrow-transaction.ts
Labels: enhancement
